#!/bin/bash
#########################################################################################
# QISSMU (Codename: ANTIVAGRANT) v.0.9
# Copyright Ichthyx 2021
# License : GNU GPL V3
##### Bash default for good behavior ####################################################
set -o errexit # (exit if error)
# Color variables:
GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'
CACHEDIR=".qissmucache" # Cache directory
#########################################################################################
##### Variables #########################################################################
#########################################################################################
# Default settings if empty
if [[ -z "$CLOUD_IMAGE" && -z "$HASH" ]];
then
  CLOUD_IMAGE="https://cloud.debian.org/cdimage/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2"
  HASH="https://cloud.debian.org/cdimage/cloud/bullseye/latest/SHA512SUMS"
fi
### NOTES:
### - links to cloud images:
###   Ubuntu http://cloud-images.ubuntu.com/
###   CentOS: http://cloud.centos.org/centos/7/images/
###   Fedora: https://alt.fedoraproject.org/cloud/
###   Flatcar (CoreOS fork): https://stable.release.flatcar-linux.net/amd64-usr/current/
###   Gentoo: http://gentoo.osuosl.org/experimental/amd64/openstack
###   Arch (also Gentoo): https://linuximages.de/openstack/arch/
###   Alpine: https://github.com/chriswayg/packer-qemu-cloud/
###   RockyLinux https://download.rockylinux.org/pub/rocky/8.4/images/

# DEFAULT VM Variables:
if [[ -z "$VM_USER_NAME" ]]; then VM_USER_NAME="testuser"; fi
if [[ -z "$VM_USER_PASSWORD" ]]; then VM_USER_PASSWORD="1234"; fi
if [[ -z "$VM_ROOT_PASSWORD" ]]; then VM_ROOT_PASSWORD=VM_USER_PASSWORD; fi
if [[ -z "$VM_MEMORY_SIZE" ]]; then VM_MEMORY_SIZE="4096"; fi
if [[ -z "$NETWORK_BRIDGE" ]]; then NETWORK_BRIDGE="br0"; fi
# NOTE : NETWORK_USERMODE_PORTREDIR=(tcp::5432-:5432 tcp::443-:443 tcp::2222-:22 udp::53-:53)
if [[ -z "$NETWORK_USERMODE_PORTREDIR" ]]; then NETWORK_USERMODE_PORTREDIR=(tcp::2222-:22); fi
if [[ -z "$HOST_CPU_CORES" ]]; then HOST_CPU_CORES=$(nproc --all); fi
if [[ -z "$QCOW_FILE" ]]; then QCOW_FILE=$(echo $CLOUD_IMAGE | awk -F '/' '{print $NF}'); fi
# Custom settings:
# RESIZE="4G"
# BTRFS_NOCOW=1
# TODO: SSH_KEY=""
# TODO: QEMU_CUST_ARGS=""


#########################################################################################
# Checking Arguments :
#########################################################################################
# TODO: better -help
while [ $# -gt 0 ]; do
  case "$1" in
    -bridge|-b)
      USE_BRIDGE=1;;
    -clean*|-c*)
      CLEAN=1;;
    -fastpls|-f)
      if [[ "$1" != *=* ]]; then shift; fi # Value is next arg if no `=`
      FASTPLS="${1#*=}"
      ;;
    -help|-h)
      echo "qissmu - [version 0.9]"
      echo "-bridge           use bridge"
      echo "-clean            delete cache folder" 
      echo "-fastpls debian   quickly dl and boot a debian image"
      exit 0
      ;;
    *)
      >&2 echo -e "${RED}[!] Invalid argument.${RESET}"
      exit 1
      ;;
  esac
  shift
done


#########################################################################################
# From now every step is a function just for better readability.
#########################################################################################$


function check_dep() {
  # Archlinux : pacman -S wget qemu libisoburn openbsd-netcat bridge-utils
  # Debian : apt install wget qemu libisoburn1 netcat-openbsd bridge-utils
  # RHEL/CentOS : TODO
  if [ ! "$(which wget)" ]; then
      echo -e "${RED}[!] wget not found please install it to run.${RESET}"
      exit 1
  elif [ ! "$(which qemu-system-x86_64)" ]; then
      echo -e "${RED}[!] qemu not found please install it to run.${RESET}"
      exit 1
  elif [ ! "$(which xorriso)" ]; then
      echo -e "${RED}[!] libisoburn not found please install it to run.${RESET}"
      exit 1
  elif [ ! "$(which nc)" ]; then
      echo -e "${RED}[!] netcat not found please install it to run.${RESET}"
      exit 1
  elif [ ! "$(which brctl)" ]; then
      echo -e "${RED}[!] bridge-utils not found please install it to run.${RESET}"
      exit 1
  fi
}


function quickboot() {
  # TODO: replace /date/ with $date
  if [[ -n "$FASTPLS" && "$FASTPLS" == "debian" ]]; 
  then
    CLOUD_IMAGE="https://cloud.debian.org/cdimage/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2"
    HASH="https://cloud.debian.org/cdimage/cloud/bullseye/latest/SHA512SUMS"
  elif [[ -n "$FASTPLS" && "$FASTPLS" == "rockylinux" ]]; 
  then
    CLOUD_IMAGE="https://download.rockylinux.org/pub/rocky/8.4/images/Rocky-8-GenericCloud-8.4-20210620.0.x86_64.qcow2"
    HASH="https://download.rockylinux.org/pub/rocky/8.4/images/CHECKSUM"
  elif [[ -n "$FASTPLS" && "$FASTPLS" == "archlinux" ]];
  then
    CLOUD_IMAGE="https://mirror.init7.net/archlinux/images/latest/Arch-Linux-x86_64-cloudimg-20211001.0.qcow2"
    HASH="https://mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg-20211001.0.qcow2.SHA256"  
  fi
}


function clear_cache() {
  # TODO: don't dl everytime when clear
  if [[ -n "$CLEAN" ]];
  then
      rm -rfv "${CACHEDIR}"
      exit
  fi
}


function download_and_verify() {
  mkdir -p "${CACHEDIR}"
  mkdir -p "${CACHEDIR}/cloudinit"
  echo -e "${GREEN}[?] Downloading image...${RESET}"
  wget -nc $CLOUD_IMAGE -P "${CACHEDIR}"
  #TODO: 
  #wget -nc $HASH -O "${CACHEDIR}/CHECKSUM"
  #wget with -nc and -O exit 1 if already exist
  curl -L $HASH -o "${CACHEDIR}/CHECKSUM"
  IMG_ALREADY_USED="${CACHEDIR}/IMG_ALREADY_USED"
  if ! test -f "$IMG_ALREADY_USED"; then
    echo -e "${GREEN}[?] Checking CHECKSUM...${RESET}"
    cd "${CACHEDIR}"
    shasum -c CHECKSUM 2> /dev/null | grep "$QCOW_FILE"
    echo -e "${GREEN}[?] Checksum: OK${RESET}"
    cd ..

    # Resize if needed
    if [[ -n "$RESIZE" ]];
    then
        echo -e "${GREEN}[?] Resizing QCOW...${RESET}"
        qemu-img resize "${CACHEDIR}/${QCOW_FILE}" +"${RESIZE}"
    fi

    # NOCOW for BTRFS
    if [[ -n "$BTRFS_NOCOW" ]];
    then
        chattr +C "${CACHEDIR}/${QCOW_FILE}"
    fi
  fi
}


function generate_cloudinit_iso {
##### Installing qemu-guest-agent #######################################################
# TODO: doesn't work anymore ?
# TODO: Libguest ? ==> apt install --no-install-recommends --no-install-suggests libguestfs-tools -y 
# and now guestfs-tools
##### Install qemu-guest-agent #####
# echo -e "${GREEN}[?] Installing qemu-guest-agent in image...${RESET}"
# virt-customize --install qemu-guest-agent --run-command "systemctl enable qemu-guest-agent" -a "${CACHEDIR}/${QCOW_FILE}"
#########################################################################################
  if ! test -f "$IMG_ALREADY_USED"; then
    echo -e "${GREEN}[?] Generating cloud-init iso...${RESET}"
    cat > "${CACHEDIR}/cloudinit/user-data"<< EOF
#cloud-config
# vim: syntax=yaml
ssh_pwauth: True
chpasswd:
  list: |
    root:${VM_ROOT_PASSWORD}
  expire: False
users:
  - name: ${VM_USER_NAME}
    sudo: ALL=(ALL) ALL
    shell: /bin/bash
    plain_text_passwd: "${VM_USER_PASSWORD}"
    lock_passwd: False
network:
  version: 1
  config:
  - type: physical
    name: eth0
    subnets:
      - type: dhcp
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - [systemctl, daemon-reload]
  - [systemctl, enable, qemu-guest-agent]
  - [systemctl, start, qemu-guest-agent]
  - echo CLOUD-INIT ENDED
growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false
EOF

    touch "${CACHEDIR}/cloudinit/meta-data"
    xorriso -as genisoimage -output "${CACHEDIR}/cloud-init.iso" -volid CIDATA -joliet -rock "${CACHEDIR}/cloudinit/user-data" "${CACHEDIR}/cloudinit/meta-data"
  fi # END if IMG_ALREADY_USED/CREATED
}


function initialize_network {
  # 1 (default) User mode network
  # 2 Bridge
  if [[ -n "$USE_BRIDGE" ]];
  then
      # Bridge network :
      # tap exist ? if no create
      if ! ip -c a | grep -q tap;
      then
          # create tap device and add in to bridge $NETWORK_BRIDGE
          echo -e "${GREEN}[?] Asking sudo for creating tap device... ${RESET}"
          sudo ip tuntap add dev tap0 mode tap
          sudo ip link set tap0 up promisc on
          sudo brctl addif "${NETWORK_BRIDGE}" tap0
      fi
      NETWORK_PARAMS="-device virtio-net,netdev=t0,id=nic0 -netdev tap,id=t0,ifname=tap0,script=no,downscript=no"
  else
      # Port redirection network
      QEMU_HOSTFWD=""
      for value in "${NETWORK_USERMODE_PORTREDIR[@]}";
      do
        QEMU_HOSTFWD+="hostfwd=${value},";
      done;
      NETWORK_PARAMS="-device virtio-net,netdev=quissmunet0 -netdev user,id=quissmunet0,${QEMU_HOSTFWD::-1}"
  fi
}


function launch_qemu {
  #TODO: display optional
  echo -e "${GREEN}[?] Launching QEMU...${RESET}"
  qemu-system-x86_64 -enable-kvm \
  -cpu host \
  -smp "${HOST_CPU_CORES}" \
  -m ${VM_MEMORY_SIZE} \
  -chardev socket,path="${CACHEDIR}/qga.sock",server=on,wait=off,id=qga0 \
  -device virtio-serial \
  -device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0 \
  -cdrom "${CACHEDIR}/cloud-init.iso" \
  ${NETWORK_PARAMS} \
  -drive file="${CACHEDIR}/${QCOW_FILE}",media=disk,if=virtio \
  -display sdl &

  touch "${CACHEDIR}/IMG_ALREADY_USED" # Dont check checksum and recreate image next time...
  # TODO: write image filename inside + | grep ==> True if found
}


function get_ip {
  if [[ -n "$USE_BRIDGE" ]];
  then
    echo -e "${GREEN}[?] Waiting for VM to start...${RESET}"

    # we wait qmp answer
    while [[ $(echo '{"execute":"guest-sync", "arguments":{"id": 1234}}' | timeout 1 nc -U "${CACHEDIR}/qga.sock") != '{"return": 1234}' ]]
    do
      sleep 1
    done

    echo -e "${GREEN}[?] VM started asking ip${RESET}"

    QISSMU_IP_ADDR=$(echo '{"execute": "guest-network-get-interfaces"}' | timeout 1 nc -U "${CACHEDIR}/qga.sock" | jq '.return[1]."ip-addresses"[0]."ip-address"' | sed 's/"//g')

    echo -e "${GREEN}[?] IP ADDRESS of VM is : ${QISSMU_IP_ADDR}${RESET}"
  else
    QISSMU_IP_ADDR="127.0.0.1:${NETWORK_USERMODE_SSHPORT}"
  fi
}

# MAIN :
check_dep
quickboot
clear_cache
download_and_verify
generate_cloudinit_iso
initialize_network
launch_qemu
get_ip